### ISSUE TITLE
issue with codes help please

### ISSUE THREAD

**Issue by arissaraiva** [NightRang3r/Broadlink-e-control-db-dump#17]
Hello I´ve installed python 2.7 on windows 10 run the first script and get this:

C:\phytonscripts>python getBroadlinkSharedData.py
ID: 1 | Name: TV
ID: 2 | Name: User-Defined Aircon
ID: 5 | Name: TV NET
ID: 6 | Name: hdmi
ID: 7 | Name: TV
ID: 8 | Name: ar cond
ID: 9 | Name: Sort in order
ID: 10 | Name: Sort in order
ID: 11 | Name: RF Socket
ID: 12 | Name: TV
ID: 13 | Name: TV
ID: 14 | Name: Livolo
ID: 15 | Name: Xbox One
ID: 16 | Name: TV
ID: 17 | Name: porch lights
ID: 18 | Name: OSVETLITEV
ID: 19 | Name: Livolo
ID: 20 | Name: Livolo
ID: 21 | Name: Traceback (most recent call last):
  File "getBroadlinkSharedData.py", line 43, in <module>
    print "ID:", jsonSubIrData[i]['id'], "| Name:", jsonSubIrData[i]['name']
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: character maps to <undefined>

does anything went wrong?

when I put broadlink_to_home_assistant_encoder.py "packet" it returns nothing what I´m doing wrong?

tks in advance

**Comment by limcheehow** [comment]
I am having a similar issue! And I am using Python 3.5 and not 2.7 (due to my work)

  File "getBroadlinkSharedData.py", line 43
    print "ID:", jsonSubIrData[i]['id'], "| Name:", jsonSubIrData[i]['name']
              ^
SyntaxError: Missing parentheses in call to 'print'

Any idea?

**Comment by NightRang3r** [comment]
@limcheehow yes, the script doesn’t support python 3 only 2.7 it’s written in the README file!

**Comment by clach04** [comment]
@arissaraiva  do you have a data file that causes this? Be interesting to see it for testing purposes.
