### ISSUE TITLE
Script un-able to parse my json response?

### ISSUE THREAD

**Issue by homeassistant01** [NightRang3r/Broadlink-e-control-db-dump#4]
Using Python version 2.7.9
Installed simplejson using pip install simplejson

Using the getBroadlinkSharedData.py script but am getting an error after selecting which database I want to parse out. See error log below:

`python getBroadlinkSharedData.py`
`ID: 1 | Name: TV`
`ID: 2 | Name: Audio`
`ID: 3 | Name: Sort in order`
`Select accessory ID: 2`
`[+] You selected:  Audio`
`Traceback (most recent call last):
  File "getBroadlinkSharedData.py", line 49, in <module>
    jsonIrCodeData = json.loads(jsonIrCode)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1090 (char 1089)
`

**Comment by NightRang3r** [comment]
Have you installed the simplejson lib ?
