### ISSUE TITLE
please help.  Newbie needs assistance

### ISSUE THREAD

**Issue by pmac2785** [NightRang3r/Broadlink-e-control-db-dump#9]
Hi,

I am getting the following error when i try and run your script getBroadlinkSharedData.py

All the files required are in the same folder.

 RESTART: C:\Users\robyn\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.6\broadlink dump\getBroadlinkSharedData.py 
Traceback (most recent call last):
  File "C:\Users\robyn\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.6\broadlink dump\getBroadlinkSharedData.py", line 27, in <module>
    jsonSubIr = open("jsonSubIr").read()
  File "C:\Users\robyn\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1179: character maps to <undefined>

**Comment by NightRang3r** [comment]
You are using python 3 this script is for python 2.7
